### ISSUE TITLE
Atari 8-bit Assemblers: settings are ignored

### ISSUE THREAD

**Issue by witoldsz** [peterdell/wudsn-ide#2] opened 2023-01-03 19:47 UTC
### What is wrong:
- `Complier/Compile` always to temp directory, the "Output folder" setting does not take any effect.
- `Compiler/Open Output Folder` does open the temp directory (instead of source as configured)
- Trying to launch the compiled xex file fails: `Cannot open output file 'C:\Users\witoldsz\AppData\Local\Temp\HelloWorld.xex' with the standard application since no application is registered for the file extension '.xex'.` **even though path to Altirra64 was set**.

The compilation itself works fine, though:
```
Compiling for hardware ATARI8BIT on 1/2/23, 5:27 AM: C:\Users\witoldsz\Downloads\Tools\ASM\MADS\mads.exe C:\Users\witoldsz\Downloads\Projects\Atari800\HelloWorld.asm -o:C:\Users\witoldsz\AppData\Local\Temp\HelloWorld.xex -p -t:C:\Users\witoldsz\AppData\Local\Temp\HelloWorld.lab -l:C:\Users\witoldsz\AppData\Local\Temp\HelloWorld.lst

Compiler 'MADS' output:

Writing listing file...
Writing object file...
13 lines of source assembled in 2 pass
29 bytes written to the object file
```

### Steps:
1. Fresh install, as described here: https://github.com/peterdell/wudsn-ide-install/issues/1#issuecomment-1368937833
2. File/Import Projects from File System: `C:\Users\witoldsz\Downloads\Projects\Atari800`
3. Open Atari800/HelloWorld.asm
4. Help/Languages/Assembler, MADS at the bottom, path to compiler: `C:\Users\witoldsz\Downloads\Tools\ASM\MADS\mads.exe`
6. Help/Languages/Assembler/Atari 8-bit Assembler/MADS/Output Folder = Source Folder
7. Help/Languages/Assembler/Atari 8-bit Assembler/MADS/User Defined Application = `C:\Users\witoldsz\Downloads\Tools\EMU\Altirra\Altirra64.exe`
7. The build processs should take place in `C:\Users\witoldsz\Downloads\Projects\Atari800`, but:
`Compiling for hardware ATARI8BIT on 1/2/23, 5:27 AM: C:\Users\witoldsz\Downloads\Tools\ASM\MADS\mads.exe C:\Users\witoldsz\Downloads\Projects\Atari800\HelloWorld.asm -o:C:\Users\witoldsz\AppData\Local\Temp\HelloWorld.xex -p -t:C:\Users\witoldsz\AppData\Local\Temp\HelloWorld.lab -l:C:\Users\witoldsz\AppData\Local\Temp\HelloWorld.lst`

This is exactly same as I have on Linux: 
- downloaded Eclipse Platform, 
- installed WUDSN plugin, 
- configured MADS compiler 
- and I could not force it to build in the project's directory (it was always `/tmp`) or launch the xex.

### Attaching the current configuration for reference:
```
#Mon Jan 02 05:41:16 PST 2023
\!/=
/configuration/org.eclipse.core.net/org.eclipse.core.net.hasMigrated=true
/instance/com.wudsn.ide.lng/asm.compiler.mads.executable.path=C\:\\Users\\witoldsz\\Downloads\\Tools\\ASM\\MADS\\mads.exe
/instance/com.wudsn.ide.lng/asm.editor.text.attribute.identifier.enum=0,0,0,,,,0
/instance/com.wudsn.ide.lng/asm.editor.text.attribute.identifier.equate=0,0,0,,,,0
/instance/com.wudsn.ide.lng/asm.editor.text.attribute.identifier.label=0,0,0,,,,0
/instance/com.wudsn.ide.lng/asm.editor.text.attribute.identifier.local=0,0,0,,,,0
/instance/com.wudsn.ide.lng/asm.editor.text.attribute.identifier.macro=0,0,0,,,,0
/instance/com.wudsn.ide.lng/asm.editor.text.attribute.identifier.procedure=0,0,0,,,,0
/instance/com.wudsn.ide.lng/asm.editor.text.attribute.identifier.structure=0,0,0,,,,0
/instance/com.wudsn.ide.lng/compiler.acme.atari8bit.output.folder.mode=SOURCE_FOLDER
/instance/com.wudsn.ide.lng/compiler.acme.atari8bit.runner.id=default_application
/instance/com.wudsn.ide.lng/compiler.acme.atari8bit.target=MOS6502
/instance/com.wudsn.ide.lng/compiler.asm6.atari8bit.output.folder.mode=SOURCE_FOLDER
/instance/com.wudsn.ide.lng/compiler.asm6.atari8bit.runner.id=default_application
/instance/com.wudsn.ide.lng/compiler.asm6.atari8bit.target=MOS6502
/instance/com.wudsn.ide.lng/compiler.atasm.atari8bit.output.folder.mode=SOURCE_FOLDER
/instance/com.wudsn.ide.lng/compiler.atasm.atari8bit.runner.id=default_application
/instance/com.wudsn.ide.lng/compiler.atasm.atari8bit.target=MOS6502
/instance/com.wudsn.ide.lng/compiler.dasm.atari8bit.output.folder.mode=SOURCE_FOLDER
/instance/com.wudsn.ide.lng/compiler.dasm.atari8bit.runner.id=default_application
/instance/com.wudsn.ide.lng/compiler.dasm.atari8bit.target=MOS6502
/instance/com.wudsn.ide.lng/compiler.kickass.atari8bit.output.folder.mode=SOURCE_FOLDER
/instance/com.wudsn.ide.lng/compiler.kickass.atari8bit.runner.id=default_application
/instance/com.wudsn.ide.lng/compiler.kickass.atari8bit.target=MOS6502
/instance/com.wudsn.ide.lng/compiler.mads.atari8bit.output.folder.mode=SOURCE_FOLDER
/instance/com.wudsn.ide.lng/compiler.mads.atari8bit.runner.id=default_application
/instance/com.wudsn.ide.lng/compiler.mads.atari8bit.runner.user_defined_application.executable.path=C\:\\Users\\witoldsz\\Downloads\\Tools\\EMU\\Altirra\\Altirra64.exe
/instance/com.wudsn.ide.lng/compiler.mads.atari8bit.target=MOS6502
/instance/com.wudsn.ide.lng/compiler.merlin32.atari8bit.output.folder.mode=SOURCE_FOLDER
/instance/com.wudsn.ide.lng/compiler.merlin32.atari8bit.runner.id=default_application
/instance/com.wudsn.ide.lng/compiler.merlin32.atari8bit.target=MOS6502
/instance/com.wudsn.ide.lng/compiler.tass.atari8bit.output.folder.mode=SOURCE_FOLDER
/instance/com.wudsn.ide.lng/compiler.tass.atari8bit.runner.id=default_application
/instance/com.wudsn.ide.lng/compiler.tass.atari8bit.target=MOS6502
/instance/com.wudsn.ide.lng/compiler.test.atari8bit.output.folder.mode=SOURCE_FOLDER
/instance/com.wudsn.ide.lng/compiler.test.atari8bit.runner.id=default_application
/instance/com.wudsn.ide.lng/compiler.test.atari8bit.target=MOS6502
/instance/com.wudsn.ide.lng/compiler.xasm.atari8bit.output.folder.mode=SOURCE_FOLDER
/instance/com.wudsn.ide.lng/compiler.xasm.atari8bit.runner.id=default_application
/instance/com.wudsn.ide.lng/compiler.xasm.atari8bit.target=MOS6502
/instance/com.wudsn.ide.lng/editor.compile.command.positioning.mode=FIRST_ERROR_OR_WARNING
/instance/com.wudsn.ide.lng/editor.content.assist.processor.default.case=LOWER_CASE
/instance/org.eclipse.core.net/org.eclipse.core.net.hasMigrated=true
/instance/org.eclipse.core.resources/encoding=UTF-8
/instance/org.eclipse.core.resources/version=1
/instance/org.eclipse.debug.ui/org.eclipse.debug.ui.PREF_LAUNCH_PERSPECTIVES=<?xml version\="1.0" encoding\="UTF-8" standalone\="no"?>\r\n<launchPerspectives/>\r\n
/instance/org.eclipse.debug.ui/preferredTargets=com.wudsn.ide.lng.breakpoint.LanguageBreakpointsTarget.ASM\:com.wudsn.ide.lng.breakpoint.LanguageBreakpointsTarget.ASM|
/instance/org.eclipse.ui.console/org.eclipse.ui.console.P_CONSOLE_WORD_WRAP=true
/instance/org.eclipse.ui.editors/tabWidth=8
/instance/org.eclipse.ui.ide/MAX_RECENT_WORKSPACES=10
/instance/org.eclipse.ui.ide/RECENT_WORKSPACES=C\:\\Users\\witoldsz\\Downloads\\Workspace 
/instance/org.eclipse.ui.ide/RECENT_WORKSPACES_PROTOCOL=3
/instance/org.eclipse.ui.ide/SHOW_RECENT_WORKSPACES=false
/instance/org.eclipse.ui.ide/SHOW_WORKSPACE_SELECTION_DIALOG=false
/instance/org.eclipse.ui.ide/platformState=1672665606366
/instance/org.eclipse.ui.ide/quickStart=false
/instance/org.eclipse.ui.ide/tipsAndTricks=true
/instance/org.eclipse.ui.navigator/org.eclipse.ui.navigator.ProjectExplorer.filterActivation=\:org.eclipse.ui.navigator.resources.filters.startsWithDot\:org.eclipse.ui.navigator.resources.nested.HideTopLevelProjectIfNested\:org.eclipse.ui.navigator.resources.nested.HideFolderWhenProjectIsShownAsNested\:
/instance/org.eclipse.ui.workbench/org.eclipse.ui.workbench.ACTIVE_NOFOCUS_TAB_BG_END=255,255,255
/instance/org.eclipse.ui.workbench/org.eclipse.ui.workbench.ACTIVE_NOFOCUS_TAB_BG_START=255,255,255
/instance/org.eclipse.ui.workbench/org.eclipse.ui.workbench.ACTIVE_NOFOCUS_TAB_TEXT_COLOR=16,16,16
/instance/org.eclipse.ui.workbench/org.eclipse.ui.workbench.ACTIVE_TAB_BG_END=255,255,255
/instance/org.eclipse.ui.workbench/org.eclipse.ui.workbench.ACTIVE_TAB_BG_START=255,255,255
/instance/org.eclipse.ui.workbench/org.eclipse.ui.workbench.INACTIVE_TAB_BG_START=242,242,242
/instance/org.eclipse.ui/showIntro=false
/instance/org.eclipse.urischeme/processedSchemes=,eclipse+command
@com.wudsn.ide.lng=1.7.2.202212270309
@org.eclipse.core.net=1.4.0.v20220813-1037
@org.eclipse.core.resources=3.18.100.v20221025-2047
@org.eclipse.debug.ui=3.17.100.v20220926-1344
@org.eclipse.ui=3.201.200.v20221024-2137
@org.eclipse.ui.console=3.11.400.v20221012-0524
@org.eclipse.ui.editors=3.14.400.v20220730-1844
@org.eclipse.ui.ide=3.20.0.v20221027-2208
@org.eclipse.ui.navigator=3.10.400.v20221024-2137
@org.eclipse.ui.workbench=3.127.0.v20221024-2137
@org.eclipse.urischeme=1.2.200.v20221024-2137
file_export_version=3.0
```

**Comment by peterdell** [comment] 2023-01-06 21:49
Thanks for reporting. You are really helping me a lot with this. I found that the complete plugin containing the individual Runners (Emulators) went missing in the build, so you only see "Operation System Default" and "User Defined Application". I've fixed this and will create a new build after also testing the folder issue (issues confirmed here).

Regarding the "Trying to launch the compiled xex file fails: Cannot open output file 'C:\Users\witoldsz\AppData\Local\Temp\HelloWorld.xex' with the standard application since no application is registered for the file extension '.xex'. even though path to Altirra64 was set."

Where did you set it? Can you provide a screenshot of the preferences?
In any case this indicates the WUDSN tries to open the .exe using the "Operating System Default" and unless you went to Altirra to register ".xex" to be executed by Altirra, there will not be a mapping in the Windows registry.
In Altirra user "Tools / Options..." and "Set File Associations"
![image](https://user-images.githubusercontent.com/10855380/211105851-63608fc4-ac2f-45b4-bf43-662b48dd0beb.png)

**Comment by witoldsz** [comment] 2023-01-07 11:19
Hi again :)

> Regarding the "Trying to launch the compiled xex file fails: Cannot open output file [...]
> Where did you set it? Can you provide a screenshot of the preferences? [...]

Here is the screenshot:
![obraz](https://user-images.githubusercontent.com/544581/211147541-0c45f536-440a-4057-bf96-20a9deb9d561.png)


You are right though, the message makes it somehow clear that it was trying to use some windows-magic thing to figure out OS level "default" application, and I was hoping for the `User Defined Application` within the `Atari 8-bit Assemblers` to take care of it. Now I can see the bug is related to the general problem you've already found, that there is also a settings called: `Default Application to open Output File` and it can be either:
- Operating System Default Application, or
- User Defined Application

Since none of these settings were actually functional, then even though I have set `User Defined Application`, it was ignored the same way as other settings over there.

**Comment by peterdell** [comment] 2023-01-08 00:55
It should be fixed with https://github.com/peterdell/wudsn-ide/commit/ee7d657e3a07127639517892a6c19f09f5285273
It was a very huge refactoring, because the old structure of preferences had grown from the first days (only assembly, only  Atar8 8-bit, only ATASM) until the last refactoring (any language, any hardware, any compiler). And there some of the "not so clean decisions of the past" caused the total mismatch of the preferences keys now.

I did only spot check on the preferences, so be prepared to find some gaps still. Thanks again for you support!

**Comment by peterdell** [comment] 2023-01-08 15:57
I had only updated the "daily" version. But when you use the installer is by default installs the "stable" version.

Stable version is now also updated. I tested it on a 2nd Windows machine and there it works now.

**Comment by elisimpson** [comment] 2023-01-09 05:02
Thanks Peter! I tried this a few days ago and rolled back pretty quickly because none of my preferences were working. I'll try again with this new build.

**Comment by peterdell** [comment] 2023-02-12 23:39
No other complaints by now, so I set this to completed.

**Closed as completed by peterdell** 2023-02-12 23:39 UTC
